
name: Docker build

on:
  push:
    paths:
      - exercise1/**
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: cd exercise1 && docker build . --file Dockerfile --tag exercise1:$(date +%s)